title: Leslie Lai's writings
description: Leslie Lai's personal blog

baseurl: ""
url: "https://lcr.github.io"

permalink: /:title

paginate: 5
paginate_path: "/page:num"

#定义文章的layout默认为post，就不用每次在yaml里面填写layout：post
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

excerpt_separator: "<!-- more -->"

markdown: kramdown

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - home.html
  - archive.html
  - about.html

algolia:
  algolia_api_key: 2c3e03751f5b259ae833fe039896ad2e
  application_id:  4X0L5EZUHF
  index_name:      jekyll