title: Leslie Lai

author: Leslie Lai

description: Leslie Lai,a Front-end developer living in Guangzhou,writing mostly about CSS and JavaScript.

keywords: Frontend development, Leslie Lai

baseurl: ""
url: "https://lcr.github.io"

plugins:
  - jekyll-sitemap

permalink: /:title/

paginate: 5
paginate_path: "/page:num/"

#reset post's layout to post
#OR: every post yaml [layout：post]
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

excerpt_separator: "<!-- more -->"

markdown: kramdown

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.html
  - archive.html

algolia:
  algolia_api_key: 2c3e03751f5b259ae833fe039896ad2e
  application_id:  4X0L5EZUHF
  index_name:      jekyll

# Google Analytics
google_analytics: UA-107157614-1