title: Leslie's Notes
description: Leslie's Notes
baseurl: ""
url: "https://lcr.github.io"
github_username:  lcr
disqus:
   shortname: lcrccr

markdown: kramdown
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Leslie Lai